### ISSUE TITLE
React components library

### ISSUE THREAD

**Issue by mars-abd** [cerner/kaiju#214]
Hello, kaiju is a cool tool for fast building web apps!
But why developer should use only Terra UI?
It will be more usefull if developers could be able to set react components directory in config like in Styleguidist.

**Comment by StephenEsser** [comment]
Hi @mars-abd,

Thanks for checking out Kaiju!

Kaiju is designed to do exactly that. 

Kaiju may have a slight bias towards Terra components, but it will allow components from any library through the use of plugins and a little additional JSON configuration. 

Check out the Terra plugin here:

https://github.com/cerner/terra-kaiju-plugin
