### ISSUE TITLE
Drag and Drop components in the work space is not working

### ISSUE THREAD

**Issue by SP046767** [cerner/kaiju#34]
# Issue Description

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Component Version:
* Browser Name and Version:
* Operating System and version (desktop or mobile):

**Comment by mjhenkes** [comment]
@SP046767 we're going to need some more information on this one...

**Comment by SP046767** [comment]
@mjhenkes , 
Thanks for looking into this. But it seems that issue has been resolved now. 
System was not allowing to drag the components and drop them in the work space.  To resolve this, I cleared out my browser's history and cookies. Now the issue is not reproducible.
Thanks.
