### ISSUE TITLE
Customizing Demographics banner

### ISSUE THREAD

**Issue by SP046767** [cerner/kaiju#38]
# Issue Description

I want to customize Demographics banner as per my requirements. Instead of Patient details, I wanted to display, Purchase Order details (e.g. Purchase Order Number, Vendor, Amount, Buyer etc). Refer the mock up below.
![image](https://user-images.githubusercontent.com/34565025/34109920-1f153e8a-e42b-11e7-972b-aafb8712c743.png)

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

Instead of displaying patient details, it should display the purchase order details as mentioned.

## Current Behavior

I am not able to modify the patient details such as DOB.

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Component Version:
* Browser Name and Version:
* Operating System and version (desktop or mobile):

**Comment by StephenEsser** [comment]
Hi @SP046767 

The Demographics Banner provides an identifiers prop for adding custom label value pairs. This is not currently available in Kaiju but is available to developers implementing the DemoGraphicsBanner in applications.

Here is some documentation with examples: http://engineering.cerner.com/terra-core/#/site/demographics-banner
