### ISSUE TITLE
Inability to add a Comment on an Item View List Item

### ISSUE THREAD

**Issue by laurunning** [cerner/kaiju#42]
# Issue Description

I am trying to add a comment line as the last line in the item view of a list item and the control will not allow it. 
![image](https://user-images.githubusercontent.com/32143728/34490718-596a5f80-efa6-11e7-8612-9ad7338f4c0a.png)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [?] Bug
- [ ] Other

## Expected Behavior

I would think it would be nice if this worked similarly to adding a comment to the item collection. 

## Current Behavior

When you click anything in the comment dropdown, it resets to the default and doesn't add anything in the workspace. 

## Steps to Reproduce

1. create a list
2. click on the item view within in
3. go to the comment drop down
4. pick something (like item view?) and nothing happens

## Environment

* Component Version: ?
* Browser Name and Version: Chrome 
* Operating System and version (desktop or mobile): Mac desktop

**Comment by StephenEsser** [comment]
@laurunning 

Do you have write access to the workspace you are trying to add the comment to?

I was unable to reproduce this issue using the steps above. 

I was able to add an Item View, Item Display Comment, and a Demographics banner as a comment to Item Views within a List.

![image](https://user-images.githubusercontent.com/6720991/34491027-72ddc58c-efa7-11e7-9d39-0287166c9121.png)

![image](https://user-images.githubusercontent.com/6720991/34491037-7d7011bc-efa7-11e7-9bd0-f1df972586ae.png)

**Comment by laurunning** [comment]
Nevermind - there is no issue.
