### ISSUE TITLE
Security Vulnerability in marked < 0.3.9

### ISSUE THREAD

**Issue by mkwhitacre** [cerner/kaiju#47]
# Issue Description
Got an email from Github with text:

```
Known moderate severity security vulnerability detected in marked < 0.3.9 defined in package-lock.json.
package-lock.json update suggested: marked ~> 0.3.9.
```

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X ] Bug
- [ ] Other

**Comment by StephenEsser** [comment]
This should be resolved with this commit: https://github.com/cerner/kaiju/pull/45
